# Generated by Django 3.0.6 on 2020-05-10 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req', models.CharField(blank=True, choices=[('Plumbing', 'Plumbing'), ('Elctrical', 'Elctrical'), ('Painting', 'Painting'), ('Cleaning', 'Cleaning')], max_length=15)),
                ('reqdesc', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(blank=True, choices=[('Andhra-Pradesh', 'Andhra-Pradesh'), ('Arunachal-Pradesh', 'Arunachal-Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Daman-and-Diu', 'Daman-And-Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal-Pradesh', 'Himachal-Pradesh'), ('Jammu-and-Kashmir', 'Jammu-And-Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya-Pradesh', 'Madhya-Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil-Nadu', 'Tamil-Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar-Pradesh', 'Uttar-Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West-Bengal', 'West-Bengal')], max_length=20)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('ccode', models.CharField(max_length=4)),
                ('sec_num', models.CharField(max_length=10)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed')], max_length=15)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField()),
                ('updatedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
